### ISSUE TITLE
import Time Some data missing 

### ISSUE THREAD

**Issue by kamlesh0606** [JingWangTW/json-schema-editor#3]
Hello,

When import File at that time , Array Data missing .

1st i make schema and Data UI photo, 
![image](https://github.com/JingWangTW/json-schema-editor/assets/3240948/1853049f-b534-4e36-80b3-a43c525c5ad6)

And Export File ,
[Schema -1.txt](https://github.com/JingWangTW/json-schema-editor/files/12715550/Schema.-1.txt)
_(Please change file name as .txt to .json)_

and then import file , 
![image](https://github.com/JingWangTW/json-schema-editor/assets/3240948/c8b1bd32-dcb5-4074-96b8-7ae6ce475012)

So inside 3 Array, missing child elements.

Please look here.

let me know , if any query or missing data.

**Comment by JingWangTW** [comment]
Thank you for reporting the issue. I could reproduce it in my environment. I will find some time to fix it.

**Comment by JingWangTW** [comment]
This should be fixed in commit ff4db47d9702bdf2e4578e55e2d65cfca176a128. Please give it a try and don't hesitate to leave any comments if any problems occur.

**Comment by kamlesh0606** [comment]
@JingWangTW  Thanks for given Support.
